NumPy : Practice Problems 


1. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
import numpy as np
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [8]:
mat=np.arange(10,50)
print(mat)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. create two arrays and stack them vertically

In [13]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


4. Create a 1d numpy array with values ranging from 0 to 8 and extract 5th element.

In [17]:
a1=np.arange(0,9)
print(a1[4])


4


5. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
a1=np.arange(0,9).reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6. Filter non-zero elements from numpy array [1,2,0,0,4,0]

In [25]:
a1=np.array([1,2,0,0,4,0])
a1[a1>0]

array([1, 2, 4])

7. Create a 10x10 array with random values and find the minimum and maximum values.

In [33]:
x = np.random.random((10,10))
# print(x)
print(x.min(),x.max())

0.010745872360515385 0.9954464946979314


8. Create a random vector of size 30 and find the mean value.

In [37]:
a1=np.random.random(30)
print(a1)
print(np.mean(a1))

[0.20672612 0.75298581 0.53270942 0.68099109 0.05178377 0.6347456
 0.63582611 0.00201687 0.55886686 0.7591965  0.58934878 0.81984388
 0.06432638 0.02500288 0.06475006 0.26657602 0.23409625 0.36180868
 0.72447821 0.23925895 0.28707336 0.50215716 0.64956841 0.90231024
 0.89729522 0.86822291 0.58836162 0.10795534 0.39720003 0.98410488]
0.47965291390348874


9. Create a 1d array of size 10 and reshape it into 2d of shape(2,5).

In [44]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a2=a1.reshape(2,5)
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


10. Create a 3*3 matrix and print it's transpose matrix

In [49]:
a1=np.array(([1,2,3],[4,5,6],[7,8,9]))
# print(a1)
a2=a1.transpose()
print(a2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


11. Create an array of 3*3 and find  max of columns.

In [54]:
a1=np.array(([10,4,3],[4,5,6],[7,8,9]))
print(a1)
a2=a1.max(axis=0)
print(a2)

[[10  4  3]
 [ 4  5  6]
 [ 7  8  9]]
[10  8  9]


12. Create two arrays of 2-D and find dot product of it.

In [57]:
a1=np.array(([1,2],[3,4]))
a2=np.array(([3,4],[5,6]))
np.dot(a1,a2)

array([[13, 16],
       [29, 36]])

13. Using given two array try to print out 3rd given array.
a = np.array(['a', 'b', 'c'], dtype=object) b = np.array([1,2,3])

output = ['a', 'bb', 'ccc']

In [76]:
a=np.array(['a','b','c'], dtype=object)
b=np.array([1,2,3])
print([a*b])

[array(['a', 'bb', 'ccc'], dtype=object)]


14. How to find common values between two arrays

In [66]:
a1=np.array(([1,2,3]))
a2=np.array(([3,5,1]))
np.intersect1d(a1,a2)



array([1, 3])

15. Find cube of a mtrix.

In [67]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1**3)

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
